/*===========================================================================
	  C++ class	definitions	exported from UnrealScript.
	  This is automatically	generated by the tools.
	  DO NOT modify	this manually! Edit	the	corresponding .uc files	instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef SWATGUI_API
#define SWATGUI_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern SWATGUI_API	FName SWATGUI_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY


// Class	UNativeBootstrap is declared in "..\SwatGui\Classes\NativeBootstrap.uc"
class SWATGUI_API	UNativeBootstrap	: public UObject
{
public:
	   DECLARE_CLASS(UNativeBootstrap,UObject,0,SwatGui)
	   NO_DEFAULT_CONSTRUCTOR(UNativeBootstrap)
};

#endif


#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack	(pop)
#endif

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(UNativeBootstrap)
#endif // VERIFY_CLASS_SIZES
